#server:
#  port: 8280
#  servlet:
#    context-path: /app-auth
spring:
#  flyway:
#    enabled: true
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ndfl?options=--search_path%3Dndfl
    username: postgres
    password: 5397


  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update

  jackson:
    default-property-inclusion: non_absent

file:
  save-into: "c:\\11"